services:
  _defaults:
    autoconfigure: true
    autowire: true
    public: true

  MintwareDe\NativeCronBundle\DependencyInjection\CronJobRegistry:

  MintwareDe\NativeCronBundle\Command\:
    resource: '../src/Command'
    exclude:
      - '../src/Command/InstallCronJobsCommand.php'

  MintwareDe\NativeCronBundle\Command\InstallCronJobsCommand:
    arguments: ['%kernel.project_dir%']

  MintwareDe\NativeCron\CrontabManager:

  MintwareDe\NativeCron\Filesystem\CrontabFileLocatorInterface:
    class: MintwareDe\NativeCronBundle\Filesystem\NoopFileLocator

  MintwareDe\NativeCron\Filesystem\FileHandlerInterface:
    class: MintwareDe\NativeCron\Filesystem\FileHandler
