services:
  _defaults:
    autoconfigure: true
    autowire: true
    public: true

  MintwareDe\NativeCronBundle\DependencyInjection\CronJobRegistry:

  MintwareDe\NativeCronBundle\Command\:
    resource: '../src/Command'
